apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linuxtips
  namespace: linuxtips
spec:
  replicas: 7
  selector:
    matchLabels:
      app: apache-linuxtips
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache-linuxtips
        version: "v2"
    spec:
      containers:
      - name: linuxtips
        image: dionitas/linuxtips-giropops:v2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30
